package com.imagetovideoapp.utils

object Constants {
    const val BASE_URL = "https://videoai-api.univenn.com/graphql"
    const val BEARER_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtYjdveDdubDA4cmMxM3lkM2Q4eTFwZTUiLCJpYXQiOjE3NDg0MjEzOTcsImV4cCI6MTc3OTk3ODk5N30.etHVx6wnnkEsaHdiGErXDOEC7KsH3lr52NtkTGk2Uvg"
    const val debounceTime = 600L
    const val ERROR = "Error"
    const val OK = "OK"
    const val ERROR_MESSAGE_PREFIX = "Hata oluştu:"
    const val VIDEO_CREATION_FAILED = "Video oluşturulamadı"
    const val VIDEOS_FETCH_FAILED = "Videolar alınamadı"
    const val STATUS_NOT_FOUND = "Status bulunamadı"
    const val VIDEO_CREATING_DESCRIPTION = "Video oluşturuluyor..."
    const val VIDEO_URL_BASE = "https://videoai-api.univenn.com/output/"
    const val VIDEO_ID_ARGUMENT_KEY = "id"
    const val UNKNOWN_ERROR_MESSAGE = "An unknown error occurred."
    const val SUCCEEDED_STATUS = "SUCCEEDED"
    const val VIDEO_GENERATION_FAILED = "Video generation failed"
    const val IMAGE_PICKER_TYPE = "image/*"
    const val ALERT_UNKNOWN_ERROR_MESSAGE = "An unknown error occurred."
    const val TIME_FORMAT = "%02d:%02d"
    const val TEMP_FILE_PREFIX = "upload_"
    const val TEMP_FILE_SUFFIX = ".jpg"
    const val AUTHORIZATION_HEADER = "Authorization"
    const val BEARER_PREFIX = "Bearer "
    const val STATUS_COMPLETED = "Completed"
    const val STATUS_PROCESSING = "Processing"
    const val UPLOAD_TEXT = "Tap here to upload an image"
    const val UPLOADED_TEXT = "Uploaded"
    const val GENERATING_TEXT = "Generating..."
    const val DOWNLOAD_TEXT = "Video Downloaded"
    const val SHARE_TEXT = "Share this video"
    const val ERROR_FETCH_VIDEO_TEXT = "Error fetching video"
    const val ERROR_SHARE_VIDEO_TEXT = "Error sharing video"
    const val ERROR_DOWNLOAD_VIDEO_TEXT = "Video indirilemedi"
    const val VIDEO_DOWNLOADING_TEXT = "Video indiriliyor..."
    const val PLEASE_UPLOAD_IMAGE_FIRST = "Please upload an image first"

}